// Generated by gencpp from file plumbing_server_client/addint.msg
// DO NOT EDIT!


#ifndef PLUMBING_SERVER_CLIENT_MESSAGE_ADDINT_H
#define PLUMBING_SERVER_CLIENT_MESSAGE_ADDINT_H

#include <ros/service_traits.h>


#include <plumbing_server_client/addintRequest.h>
#include <plumbing_server_client/addintResponse.h>


namespace plumbing_server_client
{

struct addint
{

typedef addintRequest Request;
typedef addintResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addint
} // namespace plumbing_server_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plumbing_server_client::addint > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::plumbing_server_client::addint&) { return value(); }
};

template<>
struct DataType< ::plumbing_server_client::addint > {
  static const char* value()
  {
    return "plumbing_server_client/addint";
  }

  static const char* value(const ::plumbing_server_client::addint&) { return value(); }
};


// service_traits::MD5Sum< ::plumbing_server_client::addintRequest> should match
// service_traits::MD5Sum< ::plumbing_server_client::addint >
template<>
struct MD5Sum< ::plumbing_server_client::addintRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_server_client::addint >::value();
  }
  static const char* value(const ::plumbing_server_client::addintRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_server_client::addintRequest> should match
// service_traits::DataType< ::plumbing_server_client::addint >
template<>
struct DataType< ::plumbing_server_client::addintRequest>
{
  static const char* value()
  {
    return DataType< ::plumbing_server_client::addint >::value();
  }
  static const char* value(const ::plumbing_server_client::addintRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plumbing_server_client::addintResponse> should match
// service_traits::MD5Sum< ::plumbing_server_client::addint >
template<>
struct MD5Sum< ::plumbing_server_client::addintResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_server_client::addint >::value();
  }
  static const char* value(const ::plumbing_server_client::addintResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_server_client::addintResponse> should match
// service_traits::DataType< ::plumbing_server_client::addint >
template<>
struct DataType< ::plumbing_server_client::addintResponse>
{
  static const char* value()
  {
    return DataType< ::plumbing_server_client::addint >::value();
  }
  static const char* value(const ::plumbing_server_client::addintResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUMBING_SERVER_CLIENT_MESSAGE_ADDINT_H
